# Generated by Django 4.2.6 on 2023-10-15 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('custom_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=19)),
                ('description', models.TextField()),
                ('weight_kg', models.DecimalField(decimal_places=2, max_digits=19)),
                ('weight_lbs', models.DecimalField(decimal_places=2, max_digits=19)),
                ('default_quantity', models.CharField(max_length=50)),
                ('stock', models.IntegerField(default=1)),
                ('tags', models.JSONField(blank=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='products.category')),
            ],
        ),
    ]
