# Generated by Django 4.2.6 on 2023-10-16 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='default_quantity',
            field=models.IntegerField(),
        ),
    ]
