# Generated by Django 4.2.6 on 2023-11-03 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0002_delete_blacklistedtoken_delete_storedtoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useractivities',
            name='user',
        ),
        migrations.DeleteModel(
            name='AdminLog',
        ),
        migrations.DeleteModel(
            name='UserActivities',
        ),
    ]
